name: point_of_sales
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auth:
    path: features/auth

  bottom_navigation:
    path: features/bottom_navigation

  add_product:
    path: features/add_product

  common:
    path: core/common

  ui:
    path: core/ui

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
